server:
  port: 8080
  servlet:
    context-path: /journal

spring:
  application:
    name: JournalApp

  redis :
    host : localhost
    port : 6379

  data:
    mongodb:
      uri: mongodb+srv://jayswalankit94_db_user:jayswal@cluster1.8tbvlei.mongodb.net/JournalDb
      database: JournalDb
      auto-index-creation: true


  mail:
    host: smtp.gmail.com
    port: 587
    username:  ${MAIL_USERNAME}
    password:  ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


eleven:
  api:
    key: sk_03ab0ffb9590a67e507890d2b477826b86b71b987a01fd66
    voice-id: hpp4J3VqNfWAUOO0d1Us

weather:
  api:
    key: a21cdf8ae4e549e7c00fb16d7af8361d



